const fs = require('fs');
const path = require('path');

const crew = require('../public/data/crew.json');

const enrichment = {
  'Robert Behnken': { nationality: 'American', role: 'Test Pilot, Mission Commander', bio: 'Robert L. Behnken is a NASA astronaut, former Chief of the Astronaut Office, and a U.S. Air Force colonel. He flew on STS-123 and STS-130 before commanding the historic SpaceX Demo-2 mission \u2014 the first crewed flight of Crew Dragon and the first crewed orbital spaceflight launched from the United States since STS-135 in 2011. He has performed six spacewalks totaling over 37 hours.', totalFlights: 3, spacewalks: 6 },
  'Douglas Hurley': { nationality: 'American', role: 'Test Pilot, Spacecraft Commander', bio: 'Douglas G. Hurley is a retired NASA astronaut and former U.S. Marine Corps colonel and fighter/test pilot. He piloted STS-127 and commanded STS-135, the final Space Shuttle mission. He then flew as joint commander on SpaceX Demo-2, the first crewed flight of Dragon. He retired from NASA in 2021.', totalFlights: 3, spacewalks: 0 },
  'Shannon Walker': { nationality: 'American', role: 'Mission Specialist', bio: 'Shannon Walker is a NASA astronaut and physicist. She served as a flight controller and ISS program representative before becoming an astronaut. She flew to the ISS aboard Soyuz TMA-19 in 2010 and later as a mission specialist on SpaceX Crew-1, the first operational crewed flight of Crew Dragon.', totalFlights: 2, spacewalks: 0 },
  'Soichi Noguchi': { nationality: 'Japanese', role: 'Mission Specialist', bio: 'Soichi Noguchi is a JAXA astronaut and aerospace engineer. He first flew on STS-114, the Return to Flight mission after the Columbia disaster, performing three EVAs. He later spent over five months on the ISS via Soyuz TMA-17 and flew again on SpaceX Crew-1, becoming the third person to reach space on three different types of spacecraft.', totalFlights: 3, spacewalks: 3 },
  'Victor J. Glover': { nationality: 'American', role: 'Pilot', bio: 'Victor J. Glover is a NASA astronaut and U.S. Navy captain and test pilot. He served as pilot on SpaceX Crew-1, his first spaceflight. He became the first African American to live aboard the ISS for an extended stay. He was selected as the pilot for Artemis II, which will be the first crewed mission to orbit the Moon since Apollo 17.', totalFlights: 1, spacewalks: 4 },
  'Michael S. Hopkins': { nationality: 'American', role: 'Mission Commander', bio: 'Michael S. Hopkins is a NASA astronaut and U.S. Space Force colonel \u2014 the first Space Force member to go to space. He first flew on Soyuz TMA-10M for Expedition 37/38 and commanded SpaceX Crew-1 aboard Crew Dragon Resilience. He has spent over 340 days in space across two long-duration missions.', totalFlights: 2, spacewalks: 6 },
  'Shane Kimbrough': { nationality: 'American', role: 'Mission Commander', bio: 'Shane Kimbrough is a NASA astronaut and retired U.S. Army colonel who served as a helicopter pilot and flight test engineer. He flew on STS-126 and Soyuz MS-02/Expedition 49-50 before commanding SpaceX Crew-2 aboard Crew Dragon Endeavour. He has performed multiple EVAs and spent over 388 days in space.', totalFlights: 3, spacewalks: 6 },
  'K. Megan McArthur': { nationality: 'American', role: 'Pilot', bio: 'K. Megan McArthur is a NASA astronaut and oceanographer. She operated the Canadarm2 robotic arm on STS-125, the final Hubble Space Telescope servicing mission. She later served as pilot on SpaceX Crew-2. She is married to fellow astronaut Robert Behnken.', totalFlights: 2, spacewalks: 0 },
  'Thomas Pesquet': { nationality: 'French', role: 'Mission Specialist', bio: 'Thomas Pesquet is an ESA astronaut and aerospace engineer who previously worked as an Air France pilot. He first flew to the ISS on Soyuz MS-03 for Expedition 50/51 and returned on SpaceX Crew-2, during which he served as ISS commander for Expedition 65 \u2014 the first French person to command the station.', totalFlights: 2, spacewalks: 6 },
  'Akihiko Hoshide': { nationality: 'Japanese', role: 'Mission Specialist', bio: 'Akihiko Hoshide is a JAXA astronaut and engineer. He first flew on STS-124 and then on Soyuz TMA-05M for Expedition 32/33, performing multiple EVAs. He flew again on SpaceX Crew-2 as a mission specialist and served as ISS commander for part of Expedition 65.', totalFlights: 3, spacewalks: 3 },
  'Raja Chari': { nationality: 'American', role: 'Mission Commander', bio: 'Raja Chari is a NASA astronaut and U.S. Air Force colonel and test pilot. He commanded SpaceX Crew-3 aboard Crew Dragon Endurance on his first spaceflight, spending nearly six months on the ISS for Expedition 66. He is a graduate of the U.S. Air Force Test Pilot School and MIT.', totalFlights: 1, spacewalks: 3 },
  'Thomas Marshburn': { nationality: 'American', role: 'Pilot', bio: 'Thomas Marshburn is a NASA astronaut and physician specializing in emergency medicine and aerospace medicine. He flew on STS-127 and Soyuz TMA-07M before serving as pilot on SpaceX Crew-3. During Expedition 66, he became the ISS commander. He has performed five EVAs and spent over 305 days in space.', totalFlights: 3, spacewalks: 5 },
  'Matthias Maurer': { nationality: 'German', role: 'Mission Specialist', bio: 'Matthias Maurer is an ESA astronaut and materials science engineer from Germany. He flew to the ISS as a mission specialist on SpaceX Crew-3 for Expedition 66, his first spaceflight. He performed one EVA during his nearly six-month stay on the station.', totalFlights: 1, spacewalks: 1 },
  'Jared Isaacman': { nationality: 'American', role: 'Mission Commander', bio: 'Jared Isaacman is an American billionaire entrepreneur, pilot, and commander of the Inspiration4 mission \u2014 the first all-civilian orbital spaceflight. He is the CEO of Shift4 Payments. He also commanded the Polaris Dawn mission, during which the first commercial EVA was performed. He is an accomplished jet pilot rated to fly multiple military aircraft.', totalFlights: 2, spacewalks: 1 },
  'Hayley Arceneaux': { nationality: 'American', role: 'Medical Officer', bio: "Hayley Arceneaux is a physician assistant at St. Jude Children's Research Hospital and a childhood bone cancer survivor. She flew on the Inspiration4 mission as the medical officer. At 29, she became the youngest American in orbital spaceflight and the first person with a prosthetic body part to go to space.", totalFlights: 1, spacewalks: 0 },
  'Sian Proctor': { nationality: 'American', role: 'Pilot', bio: 'Sian Proctor is an American geoscientist, explorer, STEM communicator, and astronaut analog researcher. She served as pilot on the Inspiration4 mission, becoming the fourth African American woman to go to space. She was a finalist in the 2009 NASA astronaut selection and holds a PhD in curriculum and instruction with a geology focus.', totalFlights: 1, spacewalks: 0 },
  'Christopher Sembroski': { nationality: 'American', role: 'Mission Specialist', bio: 'Christopher Sembroski is an aerospace data engineer at Lockheed Martin and a U.S. Air Force veteran. He served as a mission specialist on the Inspiration4 mission after winning his seat through a fundraiser for St. Jude. He previously worked on Minuteman III missile maintenance.', totalFlights: 1, spacewalks: 0 },
  'Kayla Barron': { nationality: 'American', role: 'Mission Specialist', bio: 'Kayla Barron is a NASA astronaut and U.S. Navy lieutenant commander and submarine warfare officer \u2014 one of the first women to serve aboard a U.S. Navy submarine. She flew on SpaceX Crew-3 as a mission specialist for Expedition 66, performing two EVAs during her stay on the ISS.', totalFlights: 1, spacewalks: 2 },
  'Michael L\u00F3pez-Alegr\u00EDa': { nationality: 'American/Spanish', role: 'Mission Commander', bio: 'Michael L\u00F3pez-Alegr\u00EDa is a former NASA astronaut and retired U.S. Navy captain who holds the American record for total EVA time. He flew on four NASA missions including STS-73, STS-92, STS-113, and a long-duration stay on Expedition 14. He commanded the Axiom Space Ax-1 mission to the ISS aboard Crew Dragon.', totalFlights: 5, spacewalks: 10 },
  'Larry Connor': { nationality: 'American', role: 'Pilot', bio: 'Larry Connor is an American entrepreneur, investor, and adventurer who served as pilot on the Axiom Space Ax-1 mission. He is notable for having traveled to the deepest part of every ocean and is an accomplished aviator. The Ax-1 mission was the first fully private crewed mission to the ISS.', totalFlights: 1, spacewalks: 0 },
  'Mark Pathy': { nationality: 'Canadian', role: 'Mission Specialist', bio: 'Mark Pathy is a Canadian businessman and philanthropist who flew on the Axiom Space Ax-1 mission as a mission specialist. He is the CEO of Mavrik Corp. During the mission, he conducted research projects focused on health topics and Earth observation from the ISS.', totalFlights: 1, spacewalks: 0 },
  'Eytan Stibbe': { nationality: 'Israeli', role: 'Mission Specialist', bio: 'Eytan Stibbe is an Israeli businessman, fighter pilot, and philanthropist who flew on the Axiom Space Ax-1 mission. He is a former Israeli Air Force F-16 pilot and the second Israeli to travel to space, after Ilan Ramon. He conducted experiments and cultural activities aboard the ISS.', totalFlights: 1, spacewalks: 0 },
  'Kjell Lindgren': { nationality: 'American', role: 'Mission Commander', bio: 'Kjell Lindgren is a NASA astronaut and physician who was born in Taipei, Taiwan. He first flew to the ISS on Soyuz TMA-17M for Expedition 44/45 and later commanded SpaceX Crew-4 aboard Crew Dragon Freedom. He has performed multiple EVAs and has logged over 300 days in space.', totalFlights: 2, spacewalks: 4 },
  'Robert Hines': { nationality: 'American', role: 'Pilot', bio: 'Robert Hines is a NASA astronaut and U.S. Army colonel, instructor pilot, and experimental test pilot. SpaceX Crew-4 was his first spaceflight, during which he served as pilot aboard Crew Dragon Freedom for Expedition 67. He spent over 170 days on the ISS.', totalFlights: 1, spacewalks: 0 },
  'Samantha Cristoforetti': { nationality: 'Italian', role: 'Mission Specialist', bio: 'Samantha Cristoforetti is an ESA astronaut and Italian Air Force pilot and engineer. She first flew on Soyuz TMA-15M for Expedition 42/43, setting the record for longest uninterrupted spaceflight by a European. She flew again on SpaceX Crew-4 and became the first European woman to command the ISS during Expedition 68.', totalFlights: 2, spacewalks: 1 },
  'Jessica Watkins': { nationality: 'American', role: 'Mission Specialist', bio: "Jessica Watkins is a NASA astronaut and geologist who has worked at NASA's Jet Propulsion Laboratory and Ames Research Center on Mars rover missions. She flew on SpaceX Crew-4 as a mission specialist for her first spaceflight, becoming the first African American woman to serve on a long-duration ISS mission.", totalFlights: 1, spacewalks: 0 },
  'Nicole Aunapu Mann': { nationality: 'American', role: 'Mission Commander', bio: 'Nicole Aunapu Mann is a NASA astronaut and U.S. Marine Corps colonel and test pilot. She commanded SpaceX Crew-5, becoming the first Native American woman to go to space. She is a member of the Wailacki of the Round Valley Indian Tribes in Northern California.', totalFlights: 1, spacewalks: 2 },
  'Josh A. Cassada': { nationality: 'American', role: 'Pilot', bio: 'Josh A. Cassada is a NASA astronaut and U.S. Navy commander and test pilot with a PhD in high-energy particle physics from the University of Rochester. He served as pilot on SpaceX Crew-5 aboard Crew Dragon Endurance, his first spaceflight. He performed multiple EVAs during Expedition 68.', totalFlights: 1, spacewalks: 3 },
  'Koichi Wakata': { nationality: 'Japanese', role: 'Mission Specialist', bio: 'Koichi Wakata is a JAXA astronaut and the most experienced Japanese astronaut. He has flown five spaceflights including STS-72, STS-92, Soyuz TMA-11M/Expedition 38-39, and SpaceX Crew-5. He served as ISS commander during Expedition 39 and has spent over 500 days in space.', totalFlights: 5, spacewalks: 0 },
  'Anna Kikina': { nationality: 'Russian', role: 'Mission Specialist', bio: 'Anna Kikina is a Roscosmos cosmonaut and the only active female Russian cosmonaut. She flew on SpaceX Crew-5 as part of a crew exchange agreement between NASA and Roscosmos. She is a civil engineer by training and was selected as a cosmonaut in 2012.', totalFlights: 1, spacewalks: 0 }
};

const enriched = crew.map(c => {
  const e = enrichment[c.name] || {};
  return { ...c, ...e };
});

const outPath = path.join(__dirname, '..', 'public', 'data', 'crew.json');
fs.writeFileSync(outPath, JSON.stringify(enriched, null, 2));
console.log('Done! Wrote', enriched.length, 'enriched crew members to crew.json');
const sample = enriched[0];
console.log('Sample bio:', sample.bio ? sample.bio.substring(0, 80) + '...' : 'NONE');
console.log('Sample role:', sample.role);
console.log('Sample nationality:', sample.nationality);
